# fly.toml app configuration file generated for green-dew-9911 on 2023-08-01T10:29:20+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "green-dew-9911"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
